title: ""
remote_theme: just-the-docs/just-the-docs

url: "https://helloDoraHacks.github.io"
baseurl: "/dorahacks-wiki"

logo: "/assets/logo.png"
logo_width: 160

permalink: pretty   # ← 就是它！

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
  nav_auto_expand: true
